name: amap_map_fluttify
description: An `Amap` Map Component, Powered By `Fluttify` Compiler, A Dart Bindings Generator For Native SDK.
version: 2.0.2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  url_launcher: ^6.1.6
  foundation_fluttify: ^0.13.0+1
  uni_map_platform_interface: ^0.7.0-rc.0
dependency_overrides:
  core_location_fluttify:
    path: ../core_location_fluttify-master
  amap_core_fluttify:
    path: ../amap_core_fluttify-0.17.0
  amap_search_fluttify:
    path: ../amap_search_fluttify-0.18.0
  amap_location_fluttify:
    path: ../amap_location_fluttify-0.22.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_map_fluttify
        pluginClass: AmapMapFluttifyPlugin
      ios:
        pluginClass: AmapMapFluttifyPlugin
      ohos:
        package: amap_map_fluttify
        pluginClass: AmapMapFluttifyPlugin